import Image from "next/image";
import Link from "next/link";
import type { Project } from "@/data/projects";

const problems = [
  ["01", "A complex customer decision", "Solar investment involves unfamiliar concepts such as capacity, expected generation, installation context, payback period, and environmental benefit. The experience needed to make that decision easier without presenting a browser estimate as a professional site assessment."],
  ["02", "Fragmented customer journeys", "Brand information, consultation, shopping, payment, and after-purchase support can easily become disconnected. Clear paths were needed for both consultation-led solar projects and transactional product orders."],
  ["03", "Content needed a central system", "Products, inventory, order statuses, installation projects, articles, and team access change over time. They require protected workflows, structured data, publication states, permissions, and reusable APIs."],
  ["04", "Trust, security, and reliability", "Customer identities, addresses, order data, inventory, and payment state require authentication, server-side authorization, validation, verified payment callbacks, transactional stock handling, and predictable errors."],
];

const features = [
  ["fa-solid fa-calculator", "Solar savings calculator", "Transforms a monthly bill into an indicative system recommendation, investment estimate, savings projection, payback period, and carbon-reduction estimate."],
  ["fa-solid fa-sun", "Service-led marketing", "Company, service, contact, and conversion sections explain the offer and repeatedly connect information to enquiry, including direct WhatsApp access."],
  ["fa-solid fa-images", "Dynamic project gallery", "Published installations support featured status, system type, size, location, completion date, client attribution, highlights, and testimonials."],
  ["fa-solid fa-newspaper", "Blog and education", "Category-aware listings and slug-based articles support solar education, maintenance advice, industry news, organic discovery, and controlled publishing."],
  ["fa-solid fa-box-open", "Product merchandising", "Categories, prices, discounts, inventory, SKUs, imagery, availability, promotional tags, details, and related products support evaluation."],
  ["fa-solid fa-cart-shopping", "Persistent cart and checkout", "Customers adjust quantities, retain the cart locally, enter shipping details, choose payment, and create orders with immutable line-item prices."],
  ["fa-solid fa-credit-card", "PayHere payment lifecycle", "Server-generated initiation, hashed requests, callback verification, payment records, and status mapping keep secrets and trust decisions server-side."],
  ["fa-solid fa-user-check", "Accounts and tracking", "Firebase identity links to customer profiles so people can manage details, review orders, inspect records, and track progress."],
  ["fa-solid fa-warehouse", "Inventory-aware orders", "Connected orders, items, products, and payments allow the service layer to manage stock during creation and cancellation."],
  ["fa-solid fa-table-columns", "Admin and publishing workflows", "Staff maintain products, orders, projects, and blogs without code changes; user management remains administrator-only."],
  ["fa-solid fa-shield-halved", "Role-based security", "The backend verifies Firebase bearer tokens and enforces STAFF and ADMIN rules on protected controllers."],
  ["fa-solid fa-magnifying-glass", "Search and social foundations", "Reusable metadata provides titles, descriptions, keywords, canonical information, Open Graph data, and Twitter-card information."],
  ["fa-solid fa-universal-access", "Responsive and accessible UI", "Reusable components, mobile layouts, lazy routes, focus states, semantic roles, considered motion, and clear feedback preserve usability."],
];

const results = [
  "Clearer communication of residential, commercial, and industrial solar services",
  "A guided decision journey through education, estimation, proof, and conversion",
  "One consistent route from product discovery to payment and order tracking",
  "A professional, responsive, and visually consistent brand presence",
  "Reduced developer dependence for products, projects, articles, and order updates",
  "Centralized operational data with structured publication and order statuses",
  "Safer separation of public browsing, customers, staff, and administrator privileges",
  "A modular platform ready for future integrations and business growth",
];

const roadmap = ["Production analytics & funnels", "Automated critical-path testing", "Transactional notifications", "CRM and managed leads", "Configurable calculator assumptions", "Richer catalog discovery", "Expanded dashboard reporting", "Formal operational reviews"];

function SolarHeading({ label, title, intro }: { label: string; title: string; intro?: string }) {
  return <div className="solar-heading"><span>{label}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div>;
}

function SolarMedia({ project, label, caption, dark = false }: { project: Project; label: string; caption: string; dark?: boolean }) {
  return <figure className={`solar-media${dark ? " is-dark" : ""}`}><div className="solar-media-visual">{project.image && <Image src={project.image} alt={`Green Light Solar Lanka project visual — ${label}`} sizes="(max-width: 800px) 100vw, 72vw" />}</div><figcaption><span>{label}</span><p>{caption}</p><small>Reserved for your final project screenshot. The existing project image is used temporarily.</small></figcaption></figure>;
}

export default function GreenLightSolarCaseStudy({ project }: { project: Project }) {
  return <main className="solar-case">
    <nav className="solar-nav"><Link href="/#projects">← Back to projects</Link><div>{project.live && <a href={project.live} target="_blank" rel="noreferrer">Website ↗</a>}{project.github && <a href={project.github} target="_blank" rel="noreferrer">Repository ↗</a>}</div></nav>

    <header className="solar-hero"><div className="solar-hero-copy"><span>Renewable energy · Commerce · Operations</span><h1>Green Light<br/><em>Solar Lanka</em></h1><p>A full-stack platform connecting company presentation, solar-system discovery, product commerce, customer accounts, online payments, publishing, and internal administration.</p><div><small>CLIENT<br/><b>Green Light Solar Lanka</b></small><small>STATUS<br/><b>Implemented platform</b></small><small>ROLE<br/><b>Full-stack delivery</b></small></div></div><div className="solar-hero-media">{project.image && <Image src={project.image} alt="Green Light Solar Lanka digital commerce and operations platform" priority sizes="(max-width: 1000px) 100vw, 46vw" />}<span>Public experience · Storefront · Admin</span></div></header>

    <section className="solar-light"><div className="solar-inner"><SolarHeading label="01 / Project introduction" title="A digital foundation for solar decisions and operations" /><div className="solar-profile">{[["Client","Green Light Solar Lanka"],["Industry","Renewable energy · Installation · Retail"],["Platform","Public web · Customer portal · Admin · API"],["Services","Strategy · UX/UI · Commerce · Payments · CMS · SEO"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div><div className="solar-copy-grid"><div><h3>The background</h3><p>Choosing a solar solution requires education, trust, technical context, visibility into previous work, and a clear route from interest to enquiry or purchase. The business also needs to maintain products, stock, orders, project stories, articles, and access without editing source code.</p><p>The project therefore extends beyond a conventional marketing site. It combines a public brand experience, solar-product store, customer tools, and an internal management application, all connected through a shared backend domain model.</p></div><div><h3>The objective</h3><p>Create a modern experience that communicates expertise, helps customers make informed decisions, supports secure product purchases, and gives the internal team a scalable foundation for daily digital operations.</p><ul><li>Present services and credibility clearly.</li><li>Connect education to calculation, quotation, contact, or purchase.</li><li>Complete commerce from discovery to tracking.</li><li>Support accounts, profiles, and order history.</li><li>Give staff controlled management access.</li><li>Establish a maintainable architecture for growth.</li></ul></div></div><SolarMedia project={project} label="Cover image" caption="Desktop storefront and administration dashboard composite." /></div></section>

    <section className="solar-dark"><div className="solar-inner"><SolarHeading label="02 / Understanding the problem" title="Two customer intents. One coherent journey." intro="One visitor may arrive with only an electricity bill and general interest; another may already know the panel, inverter, battery, or component they want to purchase. Neither path should feel secondary." /><div className="solar-problems">{problems.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="solar-discovery"><div><small>HOW WE IDENTIFIED IT</small><h3>Mapping the full customer and operational journey</h3><p>The implementation evidence supports service and proof-point review, customer-path mapping, content modelling, public/admin separation, role definition, and UI accessibility review. It does not claim interviews, analytics, or quantified research that were not recorded.</p></div><ul>{["Services, proof points, contact details, and calls to action","Awareness, calculator, enquiry, shop, payment, and tracking paths","Products, projects, articles, users, orders, items, and payments","Public, customer, staff, and administrator responsibilities","CUSTOMER, STAFF, and ADMIN permissions","Responsive layouts, focus, labels, loading, and form errors"].map(x=><li key={x}>{x}</li>)}</ul></div><blockquote className="solar-insight"><span>KEY INSIGHT</span><p>Connect education, estimation, evidence, and action. A visitor should learn, estimate a system, review real work, and then contact the team or complete a purchase—all within one consistent platform that the business can manage.</p></blockquote></div></section>

    <section className="solar-green"><div className="solar-inner"><SolarHeading label="03 / Our strategy" title="Three purpose-built applications. One source of truth." intro="Separation keeps the public experience focused and fast, gives internal users a task-oriented workspace, and allows each application to be deployed, maintained, and scaled independently." /><div className="solar-layers">{[["01","Public web application","Brand communication, customer education, solar estimation, commerce, accounts, and support."],["02","Administrative application","Products, orders, installation projects, educational articles, and controlled user management."],["03","Backend API & database","Shared data, authentication, authorization, validation, payment state, and business rules."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="solar-goals"><div><small>PROJECT GOALS</small><h3>Make the service easier to understand, act on, and manage.</h3></div><ul>{["Explain services, experience, and value","Offer decision tools and enquiry routes","Deliver purchasing and order tracking","Replace developer-dependent updates","Verify identity and role authorization","Support new content, categories, integrations, and reports"].map(x=><li key={x}>{x}</li>)}</ul></div><div className="solar-audiences">{[["Homeowners & businesses","Need clear explanations, evidence, early system guidance, and professional consultation."],["Product buyers","Prioritize specifications, pricing, stock, cart usability, payment confidence, and tracking."],["Staff & administrators","Need efficient data entry, status visibility, publishing control, and secure permissions."]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>

    <section className="solar-light"><div className="solar-inner"><SolarHeading label="04 / Our solution" title="From first question to daily operation" intro="The completed solution unifies a content-rich corporate website, decision-support calculator, shop, customer portal, backend service, and operational dashboard." /><div className="solar-solutions"><article><span>01 / PUBLIC EXPERIENCE</span><h3>Guided solar discovery</h3><p>Service pages, experience statistics, testimonials, installation galleries, educational articles, and contact routes build understanding and credibility across residential, commercial, and industrial needs.</p><p>The calculator converts a monthly electricity bill into indicative capacity, cost, savings, payback period, and annual carbon reduction. Its assumptions must be reviewed against current tariffs and market prices before production use.</p></article><article><span>02 / COMMERCE</span><h3>E-commerce and customer self-service</h3><p>The API-driven shop supports categories, details, tags, related products, persistent cart, checkout, and order creation. PayHere initiation is prepared server-side and callbacks are verified before payment and order state changes.</p><p>Firebase users synchronize with application profiles, edit their details, review orders, and track progress. Stock deduction and restoration keep inventory aligned through failure or cancellation.</p></article><article><span>03 / OPERATIONS</span><h3>Role-based content management</h3><p>The standalone dashboard provides management views for products, orders, installations, and blog posts, with administrator-only access to users. Public and protected APIs remain separate.</p><p>Products support commercial fields and availability; orders retain fulfilment, line-item, audit, and payment relationships; project and blog drafts can be prepared before publishing; Cloudinary uploads avoid exposing API secrets.</p></article></div><SolarMedia project={project} label="Public solar experience" caption="Home-page hero, services, calculator results, installation gallery, and mobile navigation." /><SolarMedia project={project} label="Commerce journey" caption="Shop, product details, cart, checkout, payment, customer orders, and tracking." dark/><SolarMedia project={project} label="Operations dashboard" caption="Dashboard summary, product editor, order table, content editor, uploader, and role controls." /></div></section>

    <section className="solar-process"><div className="solar-inner"><SolarHeading label="05 / Design & development process" title="Designed around questions, domains, and trust" /><div className="solar-process-list">{[["Discovery & research","Organized the experience around the questions a solar customer asks: what solutions exist, whether the company is credible, what system may be appropriate, what has been delivered, whether products can be bought directly, and how to get help. Those needs were mapped against internal ownership of users, products, orders, payments, projects, and blogs."],["Planning & concept development","Structured public routes around Home, About, Services, Calculator, Blog, Gallery, Contact, Shop, Account, Tracking, Privacy, and Terms. Commerce covers product detail through confirmation. Admin mirrors real management domains, with the REST API—not either frontend—holding sensitive authority."],["Design","A renewable-energy green palette, strong neutral typography, generous space, and reusable controls create consistency. Framer Motion, intersection, and count-up effects add considered feedback. Responsive Tailwind layouts, a skip link, keyboard navigation, focus treatment, semantic landmarks, labelled loading, dialogs, and alert errors support accessibility."],["Development & implementation","TypeScript spans all three apps: React/Vite and Tailwind for public and admin interfaces, with Router, Axios, form and query tooling; NestJS, Prisma, relational migrations, validation, Firebase Admin, and PayHere for the backend. Lazy routes and Suspense reduce initial bundle burden while domain modules isolate network and business responsibilities."],["Testing & refinement","Implementation checklists cover compilation, builds, lazy routes, accessibility, responsiveness, validation, loading, and visual refinement. Backend test commands exist, but reviewed source did not contain test files, so comprehensive automated coverage remains future work rather than a claimed result."]].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="solar-verification"><h3>Production verification scope</h3><div>{["Build and lint all applications","Exercise every user role","Test all PayHere callback states","Confirm concurrent stock consistency","Validate token expiry and API roles","Review calculator, content, legal, SEO, and environments","Run accessibility, browser, performance, and security checks"].map(x=><span key={x}>{x}</span>)}</div></div></div></section>

    <section className="solar-dark"><div className="solar-inner"><SolarHeading label="06 / Key features" title="One platform across the complete relationship" /><div className="solar-features">{features.map(([icon,t,d],i)=><article key={t}><div><i className={icon}/><span>{String(i+1).padStart(2,"0")}</span></div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

    <section className="solar-light"><div className="solar-inner"><SolarHeading label="07 / Technical architecture" title="Clear boundaries make future change safer" /><div className="solar-architecture"><div><i className="fa-solid fa-users"/><b>Customers</b><small>Public React app</small></div><div><i className="fa-solid fa-user-gear"/><b>Staff & admins</b><small>Admin React app</small></div><span>↓</span><div className="core"><i className="fa-solid fa-server"/><b>NestJS REST API</b><small>Auth · Roles · Validation · Rules</small></div><span>↓</span><div><i className="fa-solid fa-database"/><b>Prisma / database</b><small>Business data</small></div><div><i className="fa-solid fa-fingerprint"/><b>Firebase</b><small>Identity</small></div><div><i className="fa-solid fa-credit-card"/><b>PayHere</b><small>Payments</small></div><div><i className="fa-solid fa-cloud-arrow-up"/><b>Cloudinary</b><small>Managed images</small></div></div><div className="solar-data-model">{[["User","Firebase identity, profile, status, and CUSTOMER / STAFF / ADMIN role"],["Product","Catalog copy, price, discount, inventory, SKU, media, category, tags, and status"],["Order","Customer and fulfilment details, total, status, notes, and audit ownership"],["OrderItem","Purchased product, immutable unit price, and quantity"],["Payment","Provider, amount, verification, reference, method, and status"],["Project","Installation stories, technical facts, featured content, and testimonials"],["Blog","Authored, categorized, tagged, draft or published education"]].map(([a,b])=><article key={a}><b>{a}</b><span>{b}</span></article>)}</div><div className="solar-security"><div><span>SECURITY PRINCIPLE</span><h3>The interface guides access. The API enforces it.</h3></div><p>Firebase Admin verifies identities; role guards protect mutations; PayHere secrets and hashing stay server-side; provider notifications are verified; frontend Cloudinary configuration never contains an API secret; deployment credentials belong in managed secrets and exposed credentials must be rotated.</p></div></div></section>

    <section className="solar-results"><div className="solar-inner"><SolarHeading label="08 / Results" title="A unified digital foundation" intro="The platform replaces disconnected customer touchpoints with a clear journey from learning and estimation to evidence, contact, purchase, payment, accounts, and tracking—supported by structured internal control." /><div className="solar-results-grid">{results.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></article>)}</div><div className="solar-measure"><small>RECOMMENDED MEASUREMENT PLAN</small><p>No verified analytics, revenue, conversion, performance, or time-saving measurements were found, so numerical outcomes have not been invented. After launch, measure calculator completion, quote conversion, WhatsApp clicks, product-to-cart rate, abandonment, payment success, tracking use, organic traffic, Core Web Vitals, publishing time, and order-processing time with agreed definitions and comparison windows.</p></div></div></section>

    <section className="solar-dark"><div className="solar-inner"><div className="solar-final-grid"><div><SolarHeading label="09 / Final outcome" title="A coherent customer experience and scalable technical foundation" /><p>Green Light Solar Lanka’s platform turns a complex, high-consideration service into a clear digital journey while supporting direct product commerce and internal operations. It connects education, calculation, project and blog publishing, shopping, payments, customer accounts, tracking, role-based administration, and a structured backend.</p></div><aside><small>CLIENT TESTIMONIAL</small><blockquote>Reserved for a genuine, approved statement from the Green Light Solar Lanka team.</blockquote><p>No approved testimonial was present in the project materials, so no quotation has been presented as fact.</p></aside></div><div className="solar-roadmap">{roadmap.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></article>)}</div></div></section>

    <footer className="solar-cta"><span>HAVE A SIMILAR CHALLENGE?</span><h2>Turn complex services and operations into a clear digital platform.</h2><div><Link href="/#contact">Start a Conversation →</Link></div></footer>
  </main>;
}
