import Image from "next/image";
import Link from "next/link";
import type { Project } from "@/data/projects";

const capabilities = [
  ["fa-solid fa-location-dot", "Station discovery", "Find charging locations and access relevant station information."],
  ["fa-solid fa-signal", "Real-time availability", "Represent connector states such as available, preparing, charging, faulted, and unavailable."],
  ["fa-solid fa-bolt", "Charging sessions", "Connect user actions with active charging transactions and their completion."],
  ["fa-solid fa-credit-card", "Digital payments", "Associate session, transaction, pricing, and payment information through PayHere."],
  ["fa-solid fa-user", "Customer accounts", "Provide the account layer for profile and charging-related information."],
  ["fa-solid fa-gauge-high", "Operational management", "Give operators a centralized view of stations, connectors, users, sessions, and transactions."],
];

const workflow = ["Discover station", "Load station information", "Check connector status", "Initiate charging", "Begin OCPP communication", "Track transaction and meter data", "Associate user and session", "Process payment", "Stop session", "Store final transaction record"];

const challenges = [
  ["Physical infrastructure", "Unlike a conventional application, the platform communicates with physical EV chargers and must account for asynchronous messages, changing device state, measurements, and connectivity interruptions.", "Use a protocol-oriented central-system boundary so charger communication remains separate from customer and administration interfaces."],
  ["Real-time state", "A connector moves through operational states including Available, Preparing, Charging, Finishing, Unavailable, and Faulted.", "Model charger and connector status as explicit domain state rather than treating availability as a static database flag."],
  ["Distributed communication", "Mobile, web, APIs, backend services, databases, payments, the OCPP central system, and chargers operate as independent layers.", "Connect layers through defined interfaces and keep application, payment, and charger responsibilities separated."],
  ["Transaction consistency", "User intent, charger state, session state, meter values, billing, and payment records must refer to the same charging activity.", "Maintain traceable relationships from user to session, energy data, pricing, payment, and transaction record."],
  ["Network extensibility", "The platform should grow beyond one charger and accommodate additional stations, operators, and integrations.", "Use REST APIs and standardized OCPP communication to reduce tight coupling to a single charger or customer application."],
];

const roadmap = ["Multi-CPO roaming", "EV manufacturer integration", "Navigation-platform integration", "Advanced reservations", "Smart charging and load management", "Energy and utilization analytics", "Expanded payment and billing models"];

export default function LankaEVCaseStudy({ project }: { project: Project }) {
  return (
    <main className="ev-case-page">
      <nav className="ev-case-nav"><Link href="/#projects">← Back to projects</Link><div>{project.live && <a href={project.live} target="_blank" rel="noreferrer"><i className="fa-solid fa-globe" /> Website</a>}{project.playStore && <a href={project.playStore} target="_blank" rel="noreferrer"><i className="fa-brands fa-google-play" /> Play Store</a>}{project.github && <a href={project.github} target="_blank" rel="noreferrer"><i className="fa-brands fa-github" /> Repository</a>}</div></nav>

      <header className="ev-case-hero">
        <div className="ev-case-hero-copy"><span>EV charging & mobility platform</span><h1>Lanka EV Plus</h1><p>Building the digital infrastructure that connects EV drivers, charging stations, operators, and payments into one unified platform.</p><div><small>{project.period}</small><small>Full-stack ecosystem</small><small>Sri Lanka</small></div></div>
        <div className="ev-case-hero-visual">{project.image && <Image src={project.image} alt="Lanka EV Plus logo" priority />}<i className="fa-solid fa-charging-station" /><span>EV mobility infrastructure</span></div>
      </header>

      <section className="ev-case-overview"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>01 / Overview</span><h2>More than a charging application</h2></div><div className="ev-case-two-column"><p>Lanka EV Plus is a full-stack electric-vehicle charging and mobility platform designed to provide a centralized digital experience for EV drivers while enabling charging-station operators to manage and monitor charging infrastructure.</p><p>The ecosystem brings together customer applications, real-time charger information, user accounts, charging sessions, digital payments, operational management, API integrations, and OCPP-based communication in one extensible software platform.</p></div><div className="ev-case-impact-line"><i className="fa-solid fa-link" /><p>EV Drivers <span>↔</span> Charging Stations <span>↔</span> Charging Operators <span>↔</span> Payments <span>↔</span> Central Management</p></div></div></section>

      <section className="ev-case-dark"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>02 / The challenge</span><h2>Installing chargers is only the beginning</h2><p>Drivers need discovery, availability, session control, costs, payments, and history. Operators need station, connector, user, transaction, payment, communication, and support tooling.</p></div><div className="ev-case-audience-grid"><article><span>EV drivers need</span><ul><li>Station locations and charger types</li><li>Current availability and operational status</li><li>Charging-session start, progress, and completion</li><li>Digital payment and transaction history</li></ul></article><article><span>Operators need</span><ul><li>Station and connector management</li><li>Session, transaction, and payment visibility</li><li>Infrastructure status and charger communication</li><li>Operational and customer-support workflows</li></ul></article></div></div></section>

      <section className="ev-case-architecture"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>03 / Ecosystem architecture</span><h2>A central software layer for EV infrastructure</h2><p>The platform separates customer experience, business services, payment operations, and charger communication through defined interfaces.</p></div><div className="ev-architecture-flow"><div><i className="fa-solid fa-mobile-screen-button" /><strong>EV driver</strong><small>Flutter mobile app</small></div><span>→</span><div><i className="fa-solid fa-code" /><strong>REST APIs</strong><small>Application boundary</small></div><span>→</span><div className="is-central"><i className="fa-solid fa-server" /><strong>Backend services</strong><small>Node.js platform core</small></div><span>→</span><div><i className="fa-solid fa-tower-broadcast" /><strong>OCPP 1.6</strong><small>Central system</small></div><span>→</span><div><i className="fa-solid fa-charging-station" /><strong>EV chargers</strong><small>Physical infrastructure</small></div></div><div className="ev-service-grid"><article><i className="fa-solid fa-users" /><h3>User & account services</h3></article><article><i className="fa-solid fa-database" /><h3>Structured platform data</h3></article><article><i className="fa-solid fa-credit-card" /><h3>Payments & billing</h3></article><article><i className="fa-solid fa-gauge-high" /><h3>Operations & administration</h3></article></div></div></section>

      <section className="ev-case-dark"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>04 / Customer platform</span><h2>The EV driver experience</h2></div><div className="ev-capability-grid">{capabilities.map(([icon,title,description]) => <article key={title}><i className={icon} /><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>

      <section className="ev-case-ocpp"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>05 / Charging infrastructure</span><h2>OCPP 1.6 integration</h2><p>OCPP provides the standardized communication boundary between charge points and the central charging-management system, reducing dependence on proprietary charger integrations.</p></div><div className="ev-ocpp-layout"><div><h3>Relevant protocol capabilities</h3><div className="ev-pill-list">{["Charger registration","Status updates","User authorization","Start / stop transactions","Meter values","Remote start / stop","Connector management","Reservations","Charging profiles","Error reporting"].map(x=><small key={x}>{x}</small>)}</div></div><div><h3>Operational measurements</h3><p>Meter values can provide the basis for surfacing physical charging information through backend and customer interfaces.</p><div className="ev-measure-grid">{["Energy","Power","Current","Voltage","State of Charge","Temperature","Power factor"].map(x=><span key={x}>{x}</span>)}</div></div></div></div></section>

      <section className="ev-case-dark"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>06 / Operations</span><h2>Administration and network management</h2></div><div className="ev-case-two-column"><p>The web-based administration platform separates platform operations from the customer experience. It provides a centralized environment for managing users, stations, chargers and connectors, charging activity, transactions, platform information, and operational status.</p><p>The integration-oriented architecture is designed to evolve toward multiple Charge Point Operators. APIs and standardized protocol boundaries provide a foundation for onboarding stations and operators without rebuilding the customer platform around each charger.</p></div></div></section>

      <section className="ev-case-payments"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>07 / Payments & data</span><h2>Traceability across the charging transaction</h2></div><div className="ev-payment-flow">{["User","Charging session","Energy / transaction data","Pricing & billing","PayHere payment","Receipt / transaction record"].map((item,index)=><div key={item}><span>0{index+1}</span><strong>{item}</strong></div>)}</div><div className="ev-case-two-column"><p>MySQL supports structured relationships among users, stations, charge points, connectors, sessions, transactions, payments, locations, and operational records. Firebase supports the broader application infrastructure.</p><p>The important engineering goal is not only accepting a payment; it is preserving the relationship between the physical charging activity and the customer-facing financial record.</p></div></div></section>

      <section className="ev-case-dark"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>08 / End-to-end workflow</span><h2>From discovery to transaction record</h2></div><div className="ev-workflow-grid">{workflow.map((step,index)=><article key={step}><span>{String(index+1).padStart(2,"0")}</span><h3>{step}</h3></article>)}</div></div></section>

      <section className="ev-case-challenges"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>09 / Engineering depth</span><h2>Key technical challenges</h2></div><div className="ev-challenge-list">{challenges.map(([title,problem,decision],index)=><article key={title}><span>0{index+1}</span><div><h3>{title}</h3><p>{problem}</p></div><div><small>Engineering direction</small><p>{decision}</p></div></article>)}</div></div></section>

      <section className="ev-case-contribution"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>10 / My contribution</span><h2>Full-stack product and platform engineering</h2><p>My portfolio and experience records attribute the following areas of work to my role on the platform.</p></div><div className="ev-contribution-grid">{["Solution architecture & system design","Full-stack product development","OCPP charging-platform integration","Payment gateway and API integration","DevOps, hosting & cloud deployment","Team leadership and client collaboration"].map((item,index)=><article key={item}><span>0{index+1}</span><h3>{item}</h3></article>)}</div></div></section>

      <section className="ev-case-dark"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>11 / Impact</span><h2>A connected foundation for EV mobility</h2></div><div className="ev-case-two-column"><p>Lanka EV Plus approaches charging as a complete digital ecosystem rather than a collection of isolated stations. It connects software applications, charging infrastructure, operators, operational data, and customer transactions.</p><p>From an engineering perspective, it demonstrates work across mobile and web development, backend services, structured data, REST APIs, digital payments, real-time state, protocol integration, physical infrastructure, and administration.</p></div></div></section>

      <section className="ev-case-roadmap"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>12 / Future direction</span><h2>An extensible platform roadmap</h2><p>These are architectural opportunities enabled by the platform foundation, not claims about currently delivered functionality.</p></div><div className="ev-roadmap-grid">{roadmap.map((item,index)=><article key={item}><span>0{index+1}</span><h3>{item}</h3></article>)}</div></div></section>

      <section className="ev-case-stack"><div className="ev-case-inner"><div className="ev-case-section-heading"><span>13 / Technology stack</span><h2>Tools across every layer</h2></div><div>{[["Mobile","Flutter"],["Web","React"],["Backend","Node.js"],["Database","MySQL"],["Services","Firebase"],["API","REST"],["Charging","OCPP 1.6"],["Payments","PayHere"]].map(([area,technology])=><article key={area}><small>{area}</small><strong>{technology}</strong></article>)}</div></div></section>

      <footer className="ev-case-footer"><div><span>Next case study</span><h2>Explore more engineering work</h2></div><Link href="/#projects">Back to all projects <span>→</span></Link></footer>
    </main>
  );
}
