import Image from "next/image";
import Link from "next/link";
import type { Project } from "@/data/projects";

const problems = [
  ["01", "A fragmented driver journey", "Without one guided flow, a driver may need separate tools to identify a station, determine connector compatibility, reserve capacity, pay, and verify a charging session. This increases uncertainty at the exact moment a user needs a fast and dependable experience."],
  ["02", "Physical chargers and business software must remain synchronized", "Availability shown in an app is only valuable when it reflects the charge point’s real condition. Boot events, authorization, status changes, transaction starts and stops, meter values, reservations, and remote commands must become durable application state without losing device history."],
  ["03", "Charging revenue has multiple stakeholders", "Wallet top-ups, reserved funds, usage billing, grace periods, station pricing, membership benefits, payment records, owner earnings, payouts, and settlement reversals cannot be handled safely as a simple payment form. The system needs explicit records and auditable state transitions."],
  ["04", "Operations need one source of truth", "As the network grows, administrators require visibility across customers, owners, stations, chargers, sessions, protocol logs, pricing, settlements, and platform health. Without a consolidated control surface, investigation and routine administration become slow and error-prone."],
];

const features = [
  ["fa-solid fa-location-dot", "Charger discovery & status", "Drivers can browse charger information, inspect station and connector details, review pricing, and see operational state. Persistent configuration is combined with live runtime information so registered infrastructure can be distinguished from current availability."],
  ["fa-solid fa-qrcode", "QR-assisted charger access", "Administrators can generate or regenerate charger QR codes, and drivers can scan a code to verify the intended charger. This shortens the physical-to-digital handoff and reduces the chance of selecting the wrong unit."],
  ["fa-solid fa-bolt", "Remote charging lifecycle", "Authenticated users can start and stop charging through the app. The central system translates requests into OCPP commands and processes responses, status changes, transaction events, and meter values while the active-session view keeps the driver informed."],
  ["fa-solid fa-calendar-check", "Reservations & booking management", "Drivers can check connector availability, select a time slot, create a booking, review upcoming and historical bookings, and cancel when permitted. Background processing supports reservation expiry and charger-side commands."],
  ["fa-solid fa-wallet", "Wallet, billing & receipts", "The platform maintains wallets, transactions, locked balances, and double-entry-style ledger records. Funds can be reserved, usage billed with precise decimal calculations, unused amounts released, and receipt PDFs generated."],
  ["fa-solid fa-credit-card", "PayHere payment integration", "PayHere supports wallet funding through payment preparation, return and cancellation handling, status lookup, and server-side webhook processing. Each payment remains connected to the corresponding user and wallet transaction."],
  ["fa-solid fa-tags", "Pricing & grace-period rules", "Administrators can create and assign pricing configurations to stations. Background workers enforce time-sensitive workflows such as booking expiry and post-session grace handling consistently."],
  ["fa-solid fa-id-card", "Station memberships", "Drivers can submit and monitor membership requests. Administrators configure payment instructions, record payments, approve or reject requests, update active memberships, and revoke access."],
  ["fa-solid fa-shield-halved", "Identity & access control", "Firebase supports email/password flows, Google sign-in, verification, password recovery, and ID-token-based API access. Backend middleware distinguishes authenticated users, active users, and administrators."],
  ["fa-solid fa-chart-line", "Administration & reporting", "The admin console provides network metrics, customer and owner records, infrastructure management, pricing, sessions, settlements, payouts, revenue reports, OCPP logs, audit trails, and diagnostics with filters and pagination."],
  ["fa-solid fa-heart-pulse", "Reliability & observability", "Basic and detailed health checks expose service readiness. Request identifiers, structured errors, persistent OCPP messages, charger runtime state, live sessions, and admin audits provide several layers of traceability."],
];

const outcomes = [
  "Established one connected customer journey for charger discovery, booking, payment, charging, and history",
  "Connected mobile commands to OCPP-compatible charging infrastructure through a dedicated central system",
  "Created clearer operational visibility through live state, health checks, OCPP logs, session records, and audit trails",
  "Reduced manual financial reconstruction by modelling wallets, ledgers, payments, owner earnings, payouts, and settlements explicitly",
  "Provided self-service account, wallet, booking, membership, receipt, notification, legal, and support experiences",
  "Delivered a scalable three-application foundation with automated coverage around financially and operationally sensitive behavior",
];

const roadmap = ["Broader charger validation", "Richer mapping & route planning", "Automated owner disbursement", "Enhanced notifications & support", "Deeper product analytics", "iOS release validation", "Expanded UI automation", "Deployment observability"];

function Heading({ label, title, intro }: { label: string; title: string; intro?: string }) {
  return <div className="ev-case-section-heading"><span>{label}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div>;
}

function ImageStage({ project, label, caption, className = "" }: { project: Project; label: string; caption: string; className?: string }) {
  return <figure className={`ev-image-stage ${className}`}>
    <div>{project.image && <Image src={project.image} alt={`LankaEV+ project visual — ${label}`} sizes="(max-width: 800px) 100vw, 80vw" />}</div>
    <figcaption><span>{label}</span><p>{caption}</p><small>Replace this project visual with the final product screenshot when available.</small></figcaption>
  </figure>;
}

export default function LankaEVCaseStudy({ project }: { project: Project }) {
  return <main className="ev-case-page ev-case-expanded">
    <nav className="ev-case-nav"><Link href="/#projects">← Back to projects</Link><div>{project.live && <a href={project.live} target="_blank" rel="noreferrer"><i className="fa-solid fa-globe" /> Website</a>}{project.playStore && <a href={project.playStore} target="_blank" rel="noreferrer"><i className="fa-brands fa-google-play" /> Play Store</a>}{project.appStore && <a href={project.appStore} target="_blank" rel="noreferrer"><i className="fa-brands fa-apple" /> App Store</a>}{project.github && <a href={project.github} target="_blank" rel="noreferrer"><i className="fa-brands fa-github" /> Repository</a>}</div></nav>

    <header className="ev-case-hero"><div className="ev-case-hero-copy"><span>Connected EV charging platform</span><h1>Lanka<br/>EV Plus</h1><p>A complete ecosystem connecting EV drivers, charging stations, station owners, and administrators through one coordinated mobile, web, backend, and OCPP experience.</p><div><small>DEC 2025 — SEP 2026</small><small>FULL-STACK ECOSYSTEM</small><small>SRI LANKA</small></div></div><div className="ev-case-hero-visual ev-case-hero-image">{project.image && <Image src={project.image} alt="LankaEV+ charging station and mobile application" priority sizes="(max-width: 1000px) 100vw, 46vw" />}<span>Mobile · Web · API · OCPP 1.6</span></div></header>

    <section className="ev-case-overview"><div className="ev-case-inner"><Heading label="01 / Project introduction" title="The network behind the charging moment" /><div className="ev-profile-grid">{[["Client","LankaEV+"],["Industry","Electric mobility · EV infrastructure · Energy technology · Fintech"],["Platforms","Android Flutter app · Web admin · REST API · OCPP 1.6 central system"],["Services","Product strategy · UX/UI · Mobile, web & backend engineering · OCPP · Payments · Testing"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div><div className="ev-case-two-column ev-copy-columns"><div><h3>The background</h3><p>An EV charging service is more than a consumer-facing app. A usable charging network must coordinate physical chargers, live device state, customer identity, payments, pricing, reservations, wallet balances, operator revenue, and administrative oversight.</p><p>Each part depends on the others: a polished interface cannot complete a session if the charger protocol, billing rules, or operational controls are disconnected. LankaEV+ brings together an approachable driver app, an OCPP-compatible central system, and an administration console for managing the network and its financial operations.</p></div><div><h3>The objective</h3><p>The objective was to create a scalable digital foundation for an EV charging network: make public charging easier for drivers, give the business visibility and control over day-to-day operations, and establish reliable workflows from charger discovery through payment and settlement.</p><p>Stations, chargers, connectors, pricing plans, station owners, memberships, sessions, and settlements are represented as distinct domain entities so the platform can accommodate future network growth instead of being embedded in one rigid workflow.</p></div></div><div className="ev-at-glance">{[["Customer experience","Flutter app for authentication, charger access, bookings, charging, wallet activity, memberships, history, and support"],["Operations","React/Vite console for users, owners, stations, chargers, pricing, sessions, settlements, payouts, reports, logs, and audits"],["Platform services","Node.js/Express API, OCPP 1.6 communication, real-time charger state, business rules, and background workers"],["Data & infrastructure","MySQL with Prisma, Redis/BullMQ, Firebase, Cloudinary, PayHere, email services, and QR generation"]].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div><ImageStage project={project} label="Mobile application" caption="Primary media position for the LankaEV+ customer application overview." /></div></section>

    <section className="ev-case-dark"><div className="ev-case-inner"><Heading label="02 / Understanding the problem" title="A physical action. A time-sensitive digital transaction." intro="Drivers need confidence that they selected the correct charger, that it is available, that sufficient funds are ready, and that the session is genuinely active or stopped. Meanwhile, operators must reconcile device messages, usage measurements, balances, owner earnings, reservations, and support records." /><div className="ev-problem-grid">{problems.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="ev-discovery-block"><div><small>HOW WE IDENTIFIED THE PROBLEMS</small><h3>Domain-led discovery across every actor and state.</h3><p>The discovery process examined the whole relationship among the driver, administrator, station owner, and physical charger—not only the pages of an application.</p></div><ul>{["EV charging journey and system-requirements analysis","Driver, administrator, owner, and charger interaction mapping","OCPP 1.6 protocol and charger-command analysis","Identity, wallet, ledger, booking, session, membership, and settlement modelling","API and interface audits as all three applications evolved","Integration guides, troubleshooting records, and automated backend tests"].map(x=><li key={x}>{x}</li>)}</ul></div><blockquote className="ev-key-insight"><span>KEY INSIGHT</span><p>The charging session must be treated as a coordinated lifecycle, not an isolated screen or API request. Identity, charger state, wallet authorization, live meter data, final billing, and administrative records all need to describe the same event. That insight shaped both the backend domain model and the user experience.</p></blockquote></div></section>

    <section className="ev-case-strategy"><div className="ev-case-inner"><Heading label="03 / Our strategy" title="Three focused layers. Shared domain rules." intro="The solution separates the mobile experience, central backend, and administration console so each interface stays focused while sensitive business logic and device coordination remain centralized." /><div className="ev-strategy-layers">{[["01","Driver experience","A mobile experience optimized for the driver’s immediate tasks before, during, and after charging."],["02","Platform core","A central backend that owns charger communication, authorization, transactions, billing, and persistent records."],["03","Operations console","An administration workspace that turns complex network and financial data into manageable workflows."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="ev-goals"><div><small>PROJECT GOALS</small><h3>Reduce friction while preserving control and traceability.</h3></div><ul>{["Reduce friction from charger discovery to a completed paid session","Represent charger availability and session activity clearly and consistently","Support QR-assisted identification and remote start/stop operations","Unify wallet funding, billing, receipts, and transaction history","Enable reservations, station memberships, and customer self-service","Control infrastructure, pricing, users, owners, revenue, and exceptions","Build an extensible architecture for more stations and chargers","Preserve OCPP logs, ledgers, audits, and health checks"].map(x=><li key={x}>{x}</li>)}</ul></div><div className="ev-audiences">{[["EV drivers","Need compatible charger discovery, availability, pricing, booking, wallet funding, live monitoring, and activity history."],["Station owners","Need infrastructure and earnings represented accurately with a clear settlement and payout trail."],["Platform administrators","Need secure tools for network configuration, customer support, live sessions, history, and exceptions."],["Finance & audit users","Need structured payment, ledger, settlement, payout, and administrative-action records rather than reconstructed reports."]].map(([a,b])=><article key={a}><span>{a}</span><p>{b}</p></article>)}</div></div></section>

    <section className="ev-case-dark"><div className="ev-case-inner"><Heading label="04 / Our solution" title="One complete operating loop" intro="LankaEV+ combines a driver-facing Flutter app, an OCPP-aware Node.js central system, and a React administration console. Together they onboard users, expose infrastructure, reserve connectors, validate access and funds, issue charger commands, process meter events, calculate final charges, retain financial trails, and surface outcomes." /><div className="ev-solution-stack"><article><span>01 / MOBILE</span><h3>A guided mobile charging experience</h3><p>The protected mobile-first journey connects Firebase authentication, onboarding, email verification, QR scanning, charger browsing, bookings, wallet management, active-session monitoring, receipts, charging history, memberships, profile controls, and help content through guarded routes.</p><p>The driver receives relevant information before, during, and after charging without being exposed to the complexity of protocol and transaction layers.</p></article><article><span>02 / PLATFORM</span><h3>An OCPP-enabled charging and transaction core</h3><p>The backend is both the system of record and the bridge to physical charge points. OCPP 1.6 WebSockets handle boot notifications, authorization, status, transaction events, meter values, heartbeats, data transfer, and remote start, stop, reserve, and cancel commands.</p><p>REST services connect these events to runtime state, bookings, sessions, wallet holds, ledgers, billing, grace periods, pricing, payments, memberships, and settlements.</p></article><article><span>03 / OPERATIONS</span><h3>A unified operations and finance console</h3><p>The web console consolidates dashboards, user and owner administration, station and charger configuration, QR management, pricing, memberships, charging sessions, force-stop controls, OCPP logs, settlements, payouts, reports, audit records, and diagnostics.</p><p>Firebase ID tokens and backend authorization protect administrative routes while clear screens make protocol and financial data manageable for non-developer teams.</p></article></div><ImageStage project={project} label="Application screens" caption="Media position for the multi-screen mobile product presentation referenced after the guided charging solution." className="is-dark" /></div></section>

    <section className="ev-case-architecture"><div className="ev-case-inner"><Heading label="05 / System architecture" title="A central system for EV infrastructure" intro="Purpose-built interfaces stay focused while critical rules and device coordination remain in the platform core." /><div className="ev-architecture-flow"><div><i className="fa-solid fa-mobile-screen-button"/><strong>Flutter app</strong><small>Driver experience</small></div><span>→</span><div><i className="fa-solid fa-code"/><strong>REST APIs</strong><small>Firebase ID token</small></div><span>→</span><div className="is-central"><i className="fa-solid fa-server"/><strong>Node + Express</strong><small>Domain and billing core</small></div><span>→</span><div><i className="fa-solid fa-tower-broadcast"/><strong>OCPP 1.6</strong><small>WebSocket central system</small></div><span>→</span><div><i className="fa-solid fa-charging-station"/><strong>Charge points</strong><small>Physical network</small></div></div><div className="ev-infrastructure-row">{["Prisma + MySQL","Redis + BullMQ","Firebase Admin","PayHere","Cloudinary + email"].map(x=><span key={x}>{x}</span>)}</div><div className="ev-domain-model"><div><small>CORE DATA MODEL</small><h3>Explicit entities make the system traceable and extensible.</h3></div><div>{[["Identity & value","User · Wallet · Ledger"],["Infrastructure","Station · Charger · Connector · Runtime state"],["Charging","Pricing · Session · Live session · Booking"],["Commerce","Payment · Membership · Settlement · Payout"],["Operations","OCPP log · Admin audit · Grace job · App config"]].map(([a,b])=><article key={a}><b>{a}</b><span>{b}</span></article>)}</div></div></div></section>

    <section className="ev-case-process"><div className="ev-case-inner"><Heading label="06 / Design & development process" title="Designed around states, not screens" /><div className="ev-process-list">{[["Discovery & research","The work began by defining the actors and state transitions in an EV network. Functional requirements became customer actions, charge-point events, administrative controls, and financial consequences, supported by focused investigation of authentication, payments, wallet accounting, OCPP setup, session release, dashboards, pricing, settlements, logs, and errors."],["Planning & concept development","The platform was planned around domain boundaries rather than pages. Users, wallets, ledgers, stations, chargers, connectors, pricing, sessions, live state, bookings, memberships, payments, settlements, OCPP messages, and audits each receive dedicated representations, while frontend navigation mirrors driver intentions and operator responsibilities."],["Design","The mobile experience uses a dark-green clean-energy language, high-contrast cards, status indicators, charging imagery, prominent actions, reusable themes, tokens, widgets, loading states, and error components. The admin console increases information density through reusable cards, controls, filters, tables, and charts while separating exceptional actions from monitoring."],["Development & implementation","Flutter and Dart use Riverpod, GoRouter, Dio, secure storage, Firebase Authentication, QR scanning, WebSockets, PDF receipt generation, and PayHere. The React/Vite console uses routing, Axios, Tailwind, date-fns, Recharts, and Firebase. Node/Express combines WebSockets, Prisma/MySQL, Redis/BullMQ, validation, monetary calculations, cloud media, QR, email, and PayHere."],["Testing & refinement","Jest unit and integration suites concentrate on wallet, ledger, billing, settlements, OCPP flows, and administration. Health endpoints report server, database, and Redis status; request IDs support tracing; centralized middleware normalizes failures; and logs preserve diagnostic evidence. UI validation, loading, errors, and troubleshooting guidance support the full user-to-charger journey."]].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><ImageStage project={project} label="Mobile experience" caption="Media position for the final customer application screens and the administration experience." /></div></section>

    <section className="ev-case-dark"><div className="ev-case-inner"><Heading label="07 / Key features" title="Every stage of a charging journey" /><div className="ev-feature-grid">{features.map(([icon,t,d],i)=><article key={t}><i className={icon}/><span>{String(i+1).padStart(2,"0")}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

    <section className="ev-case-payments"><div className="ev-case-inner"><Heading label="08 / Charging lifecycle" title="Traceability from intent to receipt" /><div className="ev-payment-flow">{["Discover station","Select or reserve","Authorize user & funds","Start via OCPP","Process meter values","Bill & record"].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div><div className="ev-case-two-column"><p>The backend combines persistent charger configuration with runtime state, protects funds before charging, uses precise decimal calculations for billing, and releases unused amounts after completion.</p><p>The engineering goal is not merely accepting a payment. Every user action, charger event, energy measurement, price, payment, and transaction record must remain connected to the same session.</p></div><div className="ev-ocpp-layout"><div><h3>OCPP capabilities</h3><div className="ev-pill-list">{["Boot & heartbeat","Authorization","Status notification","Start / stop","Meter values","Remote commands","Reservations","Data transfer","Error reporting"].map(x=><small key={x}>{x}</small>)}</div></div><div><h3>Operational measurements</h3><div className="ev-measure-grid">{["Energy","Power","Current","Voltage","State of charge","Temperature","Power factor"].map(x=><span key={x}>{x}</span>)}</div></div></div></div></section>

    <section className="ev-case-challenges"><div className="ev-case-inner"><Heading label="09 / Results" title="A connected foundation for EV mobility" intro="No verified production analytics or client-approved performance figures were included in the project materials. These qualitative outcomes describe the delivered platform and its operational value without inventing metrics." /><div className="ev-result-intro"><p>The platform replaces disconnected charging tasks with a coordinated digital service. Drivers receive a clearer path from account creation to charger access and post-session records. Administrators gain a central workspace for infrastructure, people, policies, protocol activity, and financial operations.</p><p>The business gains a domain model and service architecture capable of supporting additional chargers, stations, owners, pricing arrangements, and membership programs.</p></div><div className="ev-results-grid">{outcomes.map((x,i)=><article key={x}><span>0{i+1}</span><p>{x}</p></article>)}</div><div className="ev-impact-copy"><div><h3>For drivers</h3><p>A connected customer journey and self-service access to accounts, wallets, bookings, memberships, receipts, notifications, legal information, and support.</p></div><div><h3>For operators</h3><p>Improved visibility through live runtime state, health checks, OCPP messages, session records, financial records, and administrative audits.</p></div><div><h3>For the platform</h3><p>A scalable separation of customer experience, operational control, and business logic with automated coverage around sensitive backend behavior.</p></div></div></div></section>

    <section className="ev-case-contribution"><div className="ev-case-inner"><Heading label="10 / Contribution" title="Full-stack product & platform engineering" /><div className="ev-contribution-grid">{["Solution architecture & system design","Mobile and web product development","OCPP charging-platform integration","Payment gateway & API integration","DevOps, hosting & deployment","Team leadership & client collaboration"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div><div className="ev-testimonial"><small>CLIENT TESTIMONIAL</small><blockquote>Reserved for a verified quotation from the LankaEV+ team.</blockquote><p>No client-approved testimonial was included in the supplied project materials, so no quotation has been invented.</p></div></div></section>

    <section className="ev-case-roadmap"><div className="ev-case-inner"><Heading label="11 / Final outcome & what’s next" title="A practical foundation for operating and expanding the network" /><div className="ev-case-two-column ev-copy-columns"><div><h3>Final outcome</h3><p>LankaEV+ transforms the complexity of public EV charging into one coherent product ecosystem. A user-friendly Flutter application handles the driver journey, an OCPP-enabled backend coordinates physical chargers and transaction rules, and a React administration console gives the operating team visibility and control.</p><p>The outcome is not simply an app, but a practical digital foundation for running and expanding an EV charging service.</p></div><div><h3>What’s next</h3><p>The architecture supports broader field validation across charger manufacturers, richer station mapping and route planning, automated owner disbursement, enhanced notification and support workflows, deeper product analytics, iOS release validation, expanded automated UI testing, and deployment observability.</p><p>Future phases should be prioritized using real usage, charger reliability, support cases, and settlement data.</p></div></div><div className="ev-roadmap-grid">{roadmap.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></article>)}</div></div></section>

    <section className="ev-case-stack"><div className="ev-case-inner"><Heading label="12 / Technology stack" title="Tools across every layer" /><div>{[["Mobile","Flutter · Dart · Riverpod · GoRouter"],["Admin","React · Vite · Tailwind · Recharts"],["Backend","Node.js · Express · WebSockets"],["Data","Prisma · MySQL · Decimal.js"],["Jobs","Redis · BullMQ"],["Identity","Firebase Auth · Firebase Admin"],["Charging","OCPP 1.6"],["Services","PayHere · Cloudinary · Email · QR"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</div></div></section>

    <footer className="ev-case-footer ev-case-cta"><div><span>HAVE A SIMILAR CHALLENGE?</span><h2>Turn a complex connected service into a clear digital product.</h2></div><Link href="/#contact">Start a conversation <span>→</span></Link></footer>
  </main>;
}
