import Image from "next/image";
import Link from "next/link";
import type { Project } from "@/data/projects";

const problems = [
  ["01", "A premium service needed a premium digital presence", "Mensa’s value comes from presentation, customization, quality ingredients, and attentive service. A basic catalogue would not communicate that difference. The brand needed a visual language that felt warm, polished, and occasion-led while allowing the food to remain the hero."],
  ["02", "One customer journey could not serve every type of order", "A food platter or bakery item can be purchased through a straightforward product journey. A wedding, corporate event, birthday, high tea, or custom catering request requires information about guest count, date, budget, dietary preferences, and the client’s vision."],
  ["03", "Customer activity needed to connect with operations", "Orders, quotations, contact messages, event content, gallery images, menu items, and categories all require ongoing attention. Without a centralized management layer, the team would remain dependent on fragmented messages and manual updates."],
  ["04", "The platform needed to support continued business growth", "The immediate need was a stronger customer experience, but the larger opportunity was to create a foundation for future campaigns, seasonal collections, repeat orders, customer retention, new payment options, and performance-driven marketing."],
];

const features = [
  ["Discover", "Searchable and filterable menu", "Customers can explore a live menu by category, search by product name or description, and filter by price. This reduces browsing effort while allowing Mensa to expand its catalogue without making the experience difficult to navigate."],
  ["Customize", "Product options and dynamic pricing", "Product variations allow customers to choose the option that best suits their occasion. Prices update with the selected options, creating clearer expectations before an item reaches the cart."],
  ["Order", "Cart and guided checkout", "A persistent shopping cart retains selected items and variations, supports quantity changes, and guides the customer through contact, address, delivery date, and cash-on-delivery confirmation."],
  ["Enquire", "Bespoke quote requests", "Customers planning birthdays, high teas, anniversaries, corporate events, weddings, or custom occasions can submit structured requirements instead of starting with an unorganized message."],
  ["Return", "Customer accounts, favorites, and order history", "Email and Google authentication allow customers to maintain an account, review previous orders, and return to saved favorites—supporting convenience and future repeat engagement."],
  ["Track", "Order tracking", "Customers can retrieve an order using its ID and confirm whether it is pending, confirmed, delivered, or cancelled. This adds transparency after checkout and reduces uncertainty around fulfilment."],
  ["Publish", "Events and gallery management", "Mensa can publish and update event packages and visual content from the admin area, helping the public-facing experience remain active, seasonal, and aligned with current offerings."],
  ["Manage", "Centralized lead and operations management", "The admin dashboard brings orders, quotation requests, contact messages, menu content, categories, events, gallery items, and high-level business indicators into one operational view."],
  ["Connect", "Direct WhatsApp access", "WhatsApp contact is integrated into the experience to preserve the personal, conversational service that is especially important for catering and custom orders."],
];

const outcomes = [
  "A more premium and consistent digital expression of the Mensa brand",
  "A clearer presentation of platters, bakery products, cakes, gifts, signature offerings, and event services",
  "Separate but connected conversion paths for product orders and bespoke catering enquiries",
  "A simpler customer journey across discovery, customization, cart, checkout, and tracking",
  "Centralized management of products, categories, events, gallery content, enquiries, and orders",
  "Improved visibility of customer requests and order progress for the Mensa team",
  "A stronger foundation for seasonal campaigns, content-led marketing, future payment integration, customer retention, and business expansion",
];

function SectionHeading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) {
  return <div className="mensa-v2-heading"><span>{eyebrow}</span><h2>{title}</h2>{intro && <p>{intro}</p>}</div>;
}

function BrowserMockup() {
  return <div className="mensa-browser" aria-label="Conceptual preview of the Mensa shopping experience">
    <div className="mensa-browser-bar"><i /><i /><i /><small>mensa.lk</small></div>
    <div className="mensa-browser-body"><div className="mensa-browser-copy"><Image src="/mensa/mensa-hero.png" alt="" fill sizes="70vw" /><span>CURATED FOR EVERY OCCASION</span><strong>Food made<br />memorable.</strong><button>Explore the menu</button></div><div className="mensa-browser-menu"><small>Popular choices</small>{["Signature platters", "Artisan bakery", "Bespoke cakes"].map((item, i) => <div key={item}><b>0{i + 1}</b><span>{item}</span><em>View</em></div>)}</div></div>
  </div>;
}

export default function MensaCaseStudy({ project }: { project: Project }) {
  return <main className="mensa-v2">
    <nav className="mensa-v2-nav"><Link href="/#projects">← Back to projects</Link><div><a href={project.live} target="_blank" rel="noreferrer">Visit website ↗</a><a href={project.github} target="_blank" rel="noreferrer">Repository ↗</a></div></nav>

    <header className="mensa-v2-hero">
      <div className="mensa-v2-hero-copy"><span>Luxury catering · Connected commerce</span><h1>Mensa</h1><p>Apeakstrategy partnered with Mensa to transform its premium catering offering into a refined digital ecosystem—bringing food discovery, direct ordering, bespoke event enquiries, customer communication, and day-to-day business management into one connected experience.</p><div><small>CLIENT<br /><b>Mensa</b></small><small>INDUSTRY<br /><b>Luxury catering, bakery, gifting & e-commerce</b></small><small>ROLE<br /><b>Strategy, design & development</b></small></div></div>
      <div className="mensa-v2-hero-media"><Image src="/mensa/mensa-hero.png" alt="An abundant Mensa luxury catering platter" fill priority sizes="(max-width: 1000px) 100vw, 46vw" /><span>From curated platters to bespoke celebrations</span></div>
    </header>

    <section className="mensa-v2-light"><div className="mensa-v2-inner"><SectionHeading eyebrow="01 / Project overview" title="More than a beautiful website" /><div className="mensa-v2-two-col"><div><h3>The background</h3><p>Mensa is a premium catering and food brand creating curated food platters, fresh bakery items, customized cakes, gift packages, signature dishes, and tailored catering experiences for personal, social, and corporate occasions.</p><p>As the brand’s offering expanded, Mensa needed more than a visually attractive website. It needed a digital foundation capable of presenting the quality of its products, helping customers choose between ready-to-order and customized experiences, simplifying enquiries and purchases, and supporting the team behind the scenes.</p><p>At Apeakstrategy, we approach this kind of challenge as a business ecosystem—not as an isolated software project. We worked to connect Mensa’s brand, customer journey, technology, content, and internal operations around one clear growth direction.</p></div><div><h3>The objective</h3><p>Our objective was to build a premium digital experience that made Mensa’s value immediately clear, turned visual interest into enquiries and orders, and gave the Mensa team a practical platform to manage products, events, customers, content, and fulfilment as the business grows.</p><p>The experience needed to serve two equally important customer needs:</p><ul><li>Customers who already know what they want and are ready to browse, customize, and order.</li><li>Customers planning a larger or more personal occasion who need guidance and a tailored quotation.</li></ul></div></div><figure className="mensa-v2-photo"><Image src="/mensa/mensa-celebration.png" alt="A complete Mensa catering spread prepared for a celebration" fill sizes="(max-width: 800px) 100vw, 88vw" /><figcaption>A complete Mensa spread in the context of a celebration.</figcaption></figure></div></section>

    <section className="mensa-v2-dark"><div className="mensa-v2-inner"><SectionHeading eyebrow="02 / Understanding the problem" title="Luxury is visual, personal, and operational" intro="Luxury catering is both visual and personal. Customers need to see quality before they can taste it, understand the available choices without feeling overwhelmed, and trust that the team can handle the details of an important occasion. The experience had to express a premium brand, support different buying journeys, reduce friction, and link customer requests with operations." /><div className="mensa-v2-card-grid">{problems.map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="mensa-v2-discovery"><div><small>HOW WE IDENTIFIED THE PROBLEMS</small><h3>We examined the complete relationship between Mensa and its customers—not only the pages of a website.</h3></div><ul>{["Stakeholder conversations to understand Mensa’s vision, priorities, and daily workflow", "Service and product-structure review across platters, bakery items, cakes, gifts, signature packages, and events", "Customer-journey mapping for direct purchases and consultation-led catering enquiries", "Competitor and category positioning for a distinctive premium experience", "Content, interface, and operational planning across the website, services, and dashboard", "Iterative client reviews to refine both the experience and its business fit"].map(x => <li key={x}>{x}</li>)}</ul></div></div></section>

    <section className="mensa-v2-light"><div className="mensa-v2-inner"><SectionHeading eyebrow="03 / Key insight" title="One brand. Two conversion journeys." intro="Mensa did not need a single sales funnel. It needed a connected dual journey: one path that helps customers discover and order products with ease, and another that starts a conversation around custom occasions. Both paths had to feel like the same premium brand and feed into one manageable business system." /><div className="mensa-v2-paths"><article><span>READY TO ORDER</span><h3>Defined products</h3><p>Customers can browse categories, search the menu, filter by price, view multiple images, choose variations, adjust quantities, save favorites, add products to the cart, and place an order.</p><div>Discover <b>→</b> Customize <b>→</b> Order</div></article><article><span>PLANNING AN OCCASION</span><h3>Bespoke catering</h3><p>Customers can share the event type, date, guest count, estimated budget, contact details, dietary preferences, special requirements, and their creative vision.</p><div>Enquire <b>→</b> Collaborate <b>→</b> Create</div></article></div><div className="mensa-v2-journey">{["Discover", "Choose ready-made or bespoke", "Order / request a quote", "Mensa manages the request", "Delivery and follow-up"].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></div></section>

    <section className="mensa-v2-dark"><div className="mensa-v2-inner"><SectionHeading eyebrow="04 / Our strategy" title="Five principles. One growth direction." intro="We positioned the platform around the idea that Mensa creates more than food—it creates thoughtfully curated experiences. Every layer of the solution was designed to support that promise." /><div className="mensa-v2-principles">{[["Present","Present the brand and its food with a premium, editorial visual style."],["Personalize","Personalize the journey through product variations, favorites, and custom quotation forms."],["Convert","Convert interest through clear calls to action, cart and checkout, WhatsApp access, and enquiry pathways."],["Manage","Manage orders, leads, products, events, and content through a centralized admin experience."],["Grow","Grow through a scalable digital foundation that can support future marketing, payments, campaigns, and service expansion."]].map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div><div className="mensa-v2-goals"><div><small>PROJECT GOALS</small><h3>Brand, experience, operations, and growth working as one system.</h3></div><ul>{["Establish a distinctive premium digital identity for Mensa", "Make products and catering packages easy to discover and understand", "Support direct online orders and detailed custom-event enquiries", "Make product customization and pricing clearer", "Build confidence through history and order-status tracking", "Centralize operational management for the Mensa team", "Create a flexible platform for campaigns, seasonal offerings, payments, and growth"].map(x=><li key={x}>{x}</li>)}</ul></div><div className="mensa-v2-audience"><div><small>TARGET AUDIENCE</small><h3>Made for meaningful occasions</h3><p>The primary audience includes individuals, families, professionals, and organizations looking for beautifully presented food for birthdays, anniversaries, high teas, weddings, corporate gatherings, gifting, and other meaningful occasions.</p><p>They value quality, presentation, convenience, personalization, and reliable communication. Depending on their need, they may explore the menu, save an item, place an order, request a quote, contact Mensa through WhatsApp, or return to track an order.</p></div><div>{["Intimate celebrations","Premium gifting","Corporate events"].map(x=><span key={x}>{x}</span>)}</div></div></div></section>

    <section className="mensa-v2-light"><div className="mensa-v2-inner"><SectionHeading eyebrow="05 / Our solution" title="A connected digital ecosystem" intro="We created a premium customer-facing website, commerce and enquiry journeys, a dedicated backend, and an internal management dashboard. Together, these components turn Mensa’s digital presence into an active business tool—one that attracts, converts, organizes, and supports growth." /><BrowserMockup /><div className="mensa-v2-solutions">{[["01","A premium brand and discovery experience","The website expresses warmth, craftsmanship, and understated luxury. Rich food photography, elegant typography, deep tones, warm metallic accents, considered spacing, and subtle motion create a premium editorial character without distracting from the products. Customers move naturally from Mensa’s story into menu categories, events, gallery content, and direct action across desktop and mobile."],["02","Two conversion journeys for two different needs","Ready-to-order customers can browse, search, filter, view images, choose variations, adjust quantities, save favorites, add to cart, and order with delivery details and cash-on-delivery. Custom occasions use a structured quotation journey, while direct WhatsApp access remains available for immediate conversation."],["03","A digital operations hub for the Mensa team","The administration platform centralizes menu items and categories, product variations, orders, revenue indicators, status updates, event packages, gallery content, quotation requests, and contact messages. Content can evolve with the business, and enquiries can be tracked through clear statuses and internal notes."],["04","A scalable technical and growth foundation","The platform is structured as connected customer, service, and administration layers. This separation makes it easier to maintain and creates room for card payments, campaign pages, seasonal product drops, segmentation, loyalty, marketing automation, and deeper reporting."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="mensa-v2-ecosystem">{["Customers","Mensa website","Orders · Quotes · Messages","Secure service layer","Mensa admin dashboard","Fulfilment & follow-up"].map((x,i)=><div key={x}><small>0{i+1}</small><strong>{x}</strong></div>)}</div></div></section>

    <section className="mensa-v2-process"><div className="mensa-v2-inner"><SectionHeading eyebrow="06 / Design & development process" title="From business discovery to refinement" /><div className="mensa-v2-process-grid">{[["Discovery & research","We began by understanding how Mensa creates value through taste, curation, presentation, personalization, and service. We reviewed the product range, event requirements, customer questions, and internal actions that follow every order or enquiry."],["Planning & concept development","We organized the experience around four intentions: discovering Mensa, exploring products, planning an occasion, and managing an existing order. This shaped the information architecture, calls to action, taxonomy, quotation requirements, and workflows."],["Design","The creative direction combines a deep elegant base with warm tan and gold-inspired accents, refined display typography, generous space, high-impact food imagery, glass-like surfaces, and subtle animation. It feels luxurious but approachable across mobile and desktop."],["Development & implementation","We developed a responsive Next.js, React, TypeScript, Tailwind CSS, and Framer Motion customer experience; a Node.js and Express service layer; and an internal Next.js management dashboard supported by Firebase and cloud image management."],["Testing & refinement","We refined product discovery, variation selection, cart calculations, checkout, quote submission, authentication, order retrieval, status changes, content updates, responsive behavior, loading states, validation, and error handling across customer and admin journeys."]].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="mensa-v2-brand-board"><div><small>COLOR SYSTEM</small><span className="swatch cocoa"/><span className="swatch cream"/><span className="swatch gold"/><span className="swatch sage"/></div><div><small>TYPOGRAPHY</small><strong>Refined, warm,<br/><em>occasion-led.</em></strong></div><div><small>INTERACTION</small><button>Explore menu <b>→</b></button><button className="outline">Request a quote</button></div></div><div className="mensa-v2-stack"><p><b>Customer experience</b>Next.js · React · TypeScript · Tailwind CSS · Framer Motion</p><p><b>Service layer</b>Node.js · Express · APIs · authentication · health checks</p><p><b>Operations</b>Next.js dashboard · Firebase services · cloud image management</p></div></div></section>

    <section className="mensa-v2-dark"><div className="mensa-v2-inner"><SectionHeading eyebrow="07 / Key features" title="Designed around real intentions" /><div className="mensa-v2-feature-grid">{features.map(([tag,t,d],i)=><article key={t}><span>{String(i+1).padStart(2,"0")} / {tag}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

    <section className="mensa-v2-light"><div className="mensa-v2-inner"><SectionHeading eyebrow="08 / The results" title="A stronger digital foundation" intro="Mensa now has a digital foundation that reflects the quality of its catering while supporting the practical work behind every customer interaction. The platform connects brand discovery, product exploration, ordering, custom enquiries, customer accounts, communication, content management, and fulfilment within one coherent ecosystem." /><div className="mensa-v2-result-copy"><p>For customers, this means a clearer and more confident journey from inspiration to action. For the Mensa team, it means greater control over the information customers see and a more organized way to manage orders, leads, and content.</p><p>For the business, it creates a scalable base for continued marketing, service expansion, and digital growth. No unverified metrics are used; verified figures can be added when reliable data becomes available.</p></div><div className="mensa-v2-results"><div>{outcomes.map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></article>)}</div><div className="mensa-v2-result-visual"><BrowserMockup /><div className="mensa-v2-mini-dashboard"><small>OPERATIONS OVERVIEW</small><div><b>Orders</b><span>Quotes</span><span>Events</span></div><i/><i/><i/></div></div></div></div></section>

    <section className="mensa-v2-partner"><div className="mensa-v2-inner"><div className="mensa-v2-partner-grid"><div><SectionHeading eyebrow="09 / Apeakstrategy’s role" title="More than a technology partner" /><p>At Apeakstrategy, software development is one part of a much larger commitment. We work alongside our clients to understand their business, shape the right strategy, build a distinctive brand experience, create the technology that enables it, and support the marketing and operational decisions that sustain growth.</p><p>For Mensa, this meant looking beyond pages and features. We connected how the brand presents itself, how customers make decisions, how enquiries become opportunities, how orders move through the business, and how the platform can continue evolving with the company.</p></div><div className="mensa-v2-testimonial"><small>CLIENT TESTIMONIAL</small><blockquote>Reserved for an approved reflection from the Mensa leadership team.</blockquote><p>The suggested testimonial in the document is not presented as a genuine quotation until Mensa reviews and approves it in writing.</p></div></div></div></section>

    <section className="mensa-v2-dark"><div className="mensa-v2-inner"><SectionHeading eyebrow="10 / Ecosystem at a glance" title="One connected experience" /><div className="mensa-v2-table"><div><b>Business layer</b><b>What we created</b><b>Value to Mensa</b></div>{[["Brand","Premium visual and content direction","Builds recognition, confidence, and perceived value"],["Discovery","Responsive site, menu, events, gallery, and search","Helps customers explore the complete offering"],["Conversion","Customization, cart, checkout, quotes, and WhatsApp","Supports purchases and high-value conversations"],["Relationship","Accounts, favorites, history, and tracking","Creates convenience and repeat-engagement potential"],["Operations","Admin tools for products, content, leads, and orders","Gives the team control and an organized workflow"],["Growth","SEO foundations and scalable architecture","Supports campaigns, payments, analytics, and expansion"]].map(row=><div key={row[0]}>{row.map((cell,i)=>i===0?<b key={cell}>{cell}</b>:<span key={cell}>{cell}</span>)}</div>)}</div></div></section>

    <section className="mensa-v2-future"><Image src="/mensa/mensa-celebration.png" alt="An elegant catered event representing Mensa’s path forward" fill sizes="100vw" /><div/><div className="mensa-v2-inner"><SectionHeading eyebrow="11 / Final outcome & what’s next" title="Built to keep evolving" /><p>By combining business thinking, brand storytelling, experience design, and modern technology, Apeakstrategy helped turn Mensa’s premium catering proposition into a connected digital business experience. The result is not simply a place to view food; it is a platform that helps customers discover, personalize, order, enquire, and stay informed while giving the Mensa team the tools to manage and grow the experience behind the scenes.</p><p>Our role does not end at launch. We continue to view Mensa as a long-term growth partnership, with opportunities to strengthen the ecosystem through online card payments, seasonal campaigns, landing pages, analytics, search visibility, customer segmentation, loyalty and repeat-order journeys, automated follow-up, campaign content, social media integration, and ongoing conversion optimization.</p><div>{["Online card payments","Seasonal campaigns","Campaign landing pages","Analytics & reporting","Search visibility","Customer segmentation","Loyalty & repeat orders","Automated follow-up","Social media integration","Conversion optimization"].map(x=><span key={x}>{x}</span>)}</div></div></section>

    <footer className="mensa-v2-cta"><span>READY TO BUILD MORE THAN A WEBSITE?</span><h2>Let’s shape the strategy, experience, and ecosystem that move a business forward.</h2><p>Apeakstrategy helps ambitious businesses connect strategy, brand, technology, marketing, and ongoing support into digital ecosystems built for meaningful growth.</p><div><Link href="/#contact">Start a Conversation →</Link></div></footer>
  </main>;
}
